### ISSUE TITLE
Italian server?

### ISSUE THREAD

**Issue by gnumanx** [korapp/plasma-nordvpn#11]
Would you like to add the Italian server please?

**Comment by korapp** [comment]
This plasmoid is just the GUI for the [nordvpn client](https://nordvpn.com/download/linux/). If you don't see Italy listed, it may be a problem with that. Make sure you are using the latest nordvpn, which at the moment is version 3.15.5.

**Comment by gnumanx** [comment]
You are right, sorry for having mention this matter.
