### ISSUE TITLE
Whoops! Cannot reach System Daemon.

### ISSUE THREAD

**Issue by norbert78x** [korapp/plasma-nordvpn#15]
[Plasmoid screenshots](https://ibb.co/2Zv1FJH)

`rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/nordvpn/nordvpnd.sock: connect: no such file or directory"
Whoops! Cannot reach System Daemon.`

Strange but this error appears right after booting only with plasmoid  installed. More strange that only when I log into the desktop very quickly. When more time passes between booting and logging in everything works as it should. Maybe the plasmoid is querying the program too quickly, before fully launching the NordVPN service, and something is blocking? NordVPN support man suggested system reset, nordvpnd service reset, reinstallation.... finally he suggested OpenVPN.... After uninstalling plasmoid, the problem disappears - only when logging in quickly the `nordvpn` command in the console takes a few or several seconds, but it works.

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 12 × 11th Gen Intel® Core™ i5-11600 @ 2.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D18
System Version: 1.0

**Comment by norbert78x** [comment]
`interval: p.isOperationInProgress ? 0 : 5000`

Ad hoc seems to help

**Comment by korapp** [comment]
Strange indeed. I tried to reproduce it, but so far no luck.
Could you check services activation sequence?
`systemd-analyze plot > boot_stat.svg`

**Comment by norbert78x** [comment]
![boot_stat](https://user-images.githubusercontent.com/103685195/191619133-8f6b5bbb-12d1-4dd5-9a28-e29265aaea14.svg)
