### ISSUE TITLE
Searching for "Seattle" causes plasmashell to crash

### ISSUE THREAD

**Issue by doug0x2a** [korapp/plasma-nordvpn#21]
I'm not sure if there is a way to search for a city (that would be a nice feature by the way; to be able to search for "Seattle" or "Vancouver" instead of "United States" or "Canada", then looking through the city list).

In any case, when I type in the first few characters of "Seattle" in the search box, it seems to run out of possible countries, then plasmashell crashes.  I'm on release 0.4.0, using KDE 5.25.5-0 (kubuntu 22.04 with backports).

It doesn't seem to happen 100% of the time.  If I type slowly there doesn't seem to be a problem, but if I type very quickly it will crash.  Other random character strings have caused it to crash as well.  I suspect any string that doesn't match a country has a possibility to cause a crash.

**Comment by korapp** [comment]
I've tried to recreate it on a VM corresponding to your setup, but no success so far.
Could you check the output of `journalctl | grep com.github.korapp.nordvpn` ?

**Comment by doug0x2a** [comment]
I see a bunch of two types of messages, but the dates do not correspond to the crashes, so I doubt that they are related:

`Aug 03 10:03:09 msi plasmashell[2138]: file:///home/doug/.local/share/plasma/plasmoids/com.github.korapp.nordvpn/contents/ui/ConnectionItem.qml:64: TypeError: Value is undefined and could not be converted to an object`

`Aug 03 19:12:33 msi plasmashell[2138]: file:///home/doug/.local/share/plasma/plasmoids/com.github.korapp.nordvpn/contents/ui/ConnectionItem.qml:79:5: QML Action: Accessible must be attached to an Item`

**Comment by doug0x2a** [comment]
I tried setting up a virtual machine to reproduce the error, and I don't have a problem with Kubuntu using just backports, but the version in backports-extra does crash.  I believe backports has KDE 5.24, where backports-extra is using 5.25.  Sorry for not specifying my system properly.  Given that the issue seems specific to that version of KDE, the problem may be on their end.
