### ISSUE TITLE
Plasma 6?

### ISSUE THREAD

**Issue by Spinnekop** [korapp/plasma-nordvpn#24]
Hi 

Any chance of upgrading this to work on plasma 6?

Thanks for a great plasmoid!

**Comment by korapp** [comment]
Sure. Porting the widget started when KDE Neon with Plasma 6 Alpha came out, but it was too unstable. I have plans to resume work, but for now I can't promise any date.

**Comment by Spinnekop** [comment]
Thanks for your efforts!!
