### ISSUE TITLE
Colors  icon in dark theme incorrect

### ISSUE THREAD

**Issue by jsaenzh01** [korapp/plasma-nordvpn#29]
**Describe the bug**
In plasma 6, icon is showed dark, in a dark theme.

**To Reproduce**
1. Install nordvpn
2. Show a dark color

**Expected behavior**
A expected a white icon in a dark color

**Screenshots**
![Captura de pantalla_20240303_050333](https://github.com/korapp/plasma-nordvpn/assets/153160490/1eff2130-2a62-4bea-8f25-24e8a8b0a06e)

**Desktop (please complete the following information):**
 - Distribution: Opensuse 15.5
 - KDE Plasma 6.0
 - KDE Frameworks 6.0
 - NordVPN 1.0

**Additional context**
Thanks for porting plasmoid so fast!

**Comment by korapp** [comment]
I've tested this on KDE Neon and the icon behaves correctly, so maybe it's a problem with the packages or the update process.

1. Have you installed Plasma 6 yourself from a third party repository (OpenSUSE Argon seems to be based on Leap 15.4)?
2. Is this a new installation or was it updated from Plasma 5?
   1. If the latter, did you use the plasmoid before?

**Comment by jsaenzh01** [comment]
Hi,
1.- I installed Kde 6.0 from Opensuse repos:
https://en.opensuse.org/SDB:KDE_repositories

`zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Qt5/openSUSE_Leap_$releasever' KDE-Qt5
zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Qt6/openSUSE_Leap_$releasever' KDE-Qt6
zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Frameworks/openSUSE_Leap_$releasever' KDE-Frameworks
zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Frameworks5/openSUSE_Leap_$releasever' KDE-Frameworks5
zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Applications/KDE_Frameworks5_openSUSE_Leap_$releasever' KDE-Applications
zypper ar -fp 75 'https://download.opensuse.org/repositories/KDE:/Extra/KDE_Applications_openSUSE_Leap_$releasever' KDE-Extra
zypper -v dup --allow-vendor-change
# TBD, not available just yet
# zypper -v install pattern:kde_plasma6

`

It's not a new installation. I have used for a long time. I have used your plasmoid since one year ago. I had to uninstall old version in order to install version 1.0. 

I also delete all config files related to plasma -> rm .config/plasma* .

I use breeze twilight theme (no dark). Maybe Its the difference. I have also reapplied the theme.
![Captura de pantalla_20240304_193715](https://github.com/korapp/plasma-nordvpn/assets/153160490/0f5a0955-868c-41be-a1e5-355607240e8d)

Thanks for answering! and I'm sorry for my english! (it's not my first language)

**Comment by korapp** [comment]
> I use breeze twilight theme (no dark). Maybe Its the difference. I have also reapplied the theme.

This is it!
It looks like Plasma 6 sets the ColorScheme-Text from Application Style, which in the case of the Twilight theme results in a dark icon on a dark panel.
I will dig deeper, but for now I see that Plasma itself has similar problems:
![Screenshot_20240305_221701](https://github.com/korapp/plasma-nordvpn/assets/3818002/4a465c6e-4c04-4478-9be9-ed8410a6fb44)
(plasmoidviewer)

**Comment by jsaenzh01** [comment]
Hi,
With your answer, I open a bug in Kde:
https://bugs.kde.org/show_bug.cgi?id=482645

Maybe it helps...
