### ISSUE TITLE
Plasmoid is running according to the left panel but don't appear on desktop

### ISSUE THREAD

**Issue by yreweb** [korapp/plasma-nordvpn#30]
I'm on Manjaro's latest stable release.

plasma-desktop 5.27.11
plasma-framework 5.115.0

I use latest nordvpn release and vpn is working fine.

Plasma-nordvpn 0.4.2 is working fine.

I try to run plasma-nordvpn latest version 1.0

I installed the plasma-nordvpn as a local file with widget manager.

According to the widget manager, I have 8 nordvpn plasmoid running. Unfortunately, they are not displayed on desktop.

![Screenshot_20240319_093452](https://github.com/korapp/plasma-nordvpn/assets/95222991/74e24017-3af4-40cc-9bb3-20b9687357c8)

For the second attempt, I removed the /home/user/.local/share/plasma/plasmoids/com.github.korapp.nordvpn folder, and I installed nordvpn plasmoid via command line. No error message...

I also cleaned /home/user/.config/plasma-org.kde.plasma.desktop-appletsrc between first and second attempt. I had no results so I decided to replace plasma-org.kde.plasma.desktop-appletsrc with the backup file I did before I cleaned

I rebooted multiple times.

Does someone experiences de same problem ?

Thanks.

**Comment by korapp** [comment]
I think you might have missed the change log/requirements: v1.x is for Plasma 6.

**Comment by yreweb** [comment]
Ooo my mistake, thanks
